require("basic.options")
require("basic.remap")

require("plugins")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.comment")
require("plugins.diffview")
require("plugins.gitsigns")
require("plugins.indentline")
require("plugins.lualine")
require("plugins.nvim-autopairs")
require("plugins.nvim-surround")
require("plugins.nvim-tree")
require("plugins.symbols-outline")
require("plugins.telescope")
require("plugins.test-coverage")
require("plugins.toggleterm")
require("plugins.treesitter")
require("plugins.trouble")

require("plugins.lsp")

require("plugins.dap")
